<img src='https://img.pokemondb.net/artwork/large/woobat.jpg' style="width:150px;height:100px;">

In [294]:
import matplotlib as plt
import pandas as pd
import numpy as np

import sklearn
import sklearn.feature_extraction.text as sklearnText
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [295]:
train_set = pd.read_csv("Data/train_data.csv")
train_labels = pd.read_csv("Data/train_labels.csv")
train_set = pd.merge(train_set, train_labels, on='id')
train_set

id                                          question1  \
0            0  What is the step by step guide to invest in sh...   
1            1  What is the story of Kohinoor (Koh-i-Noor) Dia...   
2            2  How can I increase the speed of my internet co...   
3            3  Why am I mentally very lonely? How can I solve...   
4            4  Which one dissolve in water quikly sugar, salt...   
5            5  Astrology: I am a Capricorn Sun Cap moon and c...   
6            6                                Should I buy tiago?   
7            7                     How can I be a good geologist?   
8            8                    When do you use シ instead of し?   
9            9  Motorola (company): Can I hack my Charter Moto...   
10          10  Method to find separation of slits using fresn...   
11          11        How do I read and find my YouTube comments?   
12          12               What can make Physics easy to learn?   
13          13        What was your first sexual experience like?   
14          14  What are the laws to change your status from a...   
15          16                       What does manipulation mean?   
16          17  Why do girls want to be friends with the guy t...   
17          18  Why are so many Quora users posting questions ...   
18          19  Which is the best digital marketing institutio...   
19          22    What are the questions should not ask on Quora?   
20          24  What does it mean that every time I look at th...   
21          25  What are some tips on making it through the jo...   
22          26                           What is web application?   
23          27  Does society place too much importance on sports?   
24          28             What is best way to make money online?   
25          29             How should I prepare for CA final law?   
26          30      What's one thing you would like to do better?   
27          31  What are some special cares for someone with a...   
28          32  What Game of Thrones villain would be the most...   
29          33  Does the United States government still blackl...   
...        ...                                                ...   
323134  404253             How do I make website like fmovies.to?   
323135  404255                 Does IBM Watson use ElasticSearch?   
323136  404256  What are some of the most common questions ask...   
323137  404257             What is Bitcoin? Is it legal in India?   
323138  404258  What is the difference between a psychologist ...   
323139  404259  What do you think is wrong with Indian schools...   
323140  404260                   Which phone is best under 12000?   
323141  404261  Who is the overall most popular Game of Throne...   
323142  404262          How do you troubleshoot a Toshiba laptop?   
323143  404266  What is the green dot next to the phone icon o...   
323144  404267  What are the causes of the fall of the Roman E...   
323145  404268  Why don't we still do great music like in the ...   
323146  404271  Does Stalin have any grandchildren that are st...   
323147  404272  What are the best new car products or inventio...   
323148  404273    What happens if you put milk in a coffee maker?   
323149  404274  Will the next generation of parenting change o...   
323150  404275  In accounting, why do we debit expenses and cr...   
323151  404276                         What is copilotsearch.com?   
323152  404277                            What does analytics do?   
323153  404279  What is the minimum time required to build a f...   
323154  404280  What are some outfit ideas to wear to a frat p...   
323155  404281  Why is Manaphy childish in Pokémon Ranger and ...   
323156  404282        How does a long distance relationship work?   
323157  404283  What do you think of the removal of the MagSaf...   
323158  404284         What does Jainism say about homosexuality?   
323159  404285  How many keywords are there in the Racket prog...   
323160  40

In [296]:
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

In [297]:
train_set['merged'] = train_set['question1'] + '!SPLIT!' + train_set['question2']

In [298]:
def calcFuzzRation(merged):
    merged = str(merged)
    merged = merged.split('!SPLIT!')
    try:
        fuzzRatio = fuzz.ratio(merged[0],merged[1])
    except:
        fuzzRatio = 0
    
    return fuzzRatio

def calcFuzzPartial(merged):
    merged = str(merged)
    merged = merged.split('!SPLIT!')
    try:
        fuzzRatio = fuzz.partial_ratio(merged[0],merged[1])
    except:
        fuzzRatio = 0
    
    return fuzzRatio

def calcFuzzTokenSort(merged):
    merged = str(merged)
    merged = merged.split('!SPLIT!')
    try:
        fuzzRatio = fuzz.token_sort_ratio(merged[0],merged[1])
    except:
        fuzzRatio = 0
    
    return fuzzRatio

def calcFuzzTokenSet(merged):
    merged = str(merged)
    merged = merged.split('!SPLIT!')
    try:
        fuzzRatio = fuzz.token_set_ratio(merged[0],merged[1])
    except:
        fuzzRatio = 0
    
    return fuzzRatio

In [299]:
train_set['fuzzRatio'] = train_set['merged'].apply(calcFuzzRation)

In [300]:
train_set['fuzzPartial'] = train_set['merged'].apply(calcFuzzPartial)

In [301]:
train_set['fuzzTokenSort'] = train_set['merged'].apply(calcFuzzTokenSort)

In [302]:
train_set['fuzzTokenSet'] = train_set['merged'].apply(calcFuzzTokenSet)

In [303]:
train_set

id                                          question1  \
0            0  What is the step by step guide to invest in sh...   
1            1  What is the story of Kohinoor (Koh-i-Noor) Dia...   
2            2  How can I increase the speed of my internet co...   
3            3  Why am I mentally very lonely? How can I solve...   
4            4  Which one dissolve in water quikly sugar, salt...   
5            5  Astrology: I am a Capricorn Sun Cap moon and c...   
6            6                                Should I buy tiago?   
7            7                     How can I be a good geologist?   
8            8                    When do you use シ instead of し?   
9            9  Motorola (company): Can I hack my Charter Moto...   
10          10  Method to find separation of slits using fresn...   
11          11        How do I read and find my YouTube comments?   
12          12               What can make Physics easy to learn?   
13          13        What was your first sexual experience like?   
14          14  What are the laws to change your status from a...   
15          16                       What does manipulation mean?   
16          17  Why do girls want to be friends with the guy t...   
17          18  Why are so many Quora users posting questions ...   
18          19  Which is the best digital marketing institutio...   
19          22    What are the questions should not ask on Quora?   
20          24  What does it mean that every time I look at th...   
21          25  What are some tips on making it through the jo...   
22          26                           What is web application?   
23          27  Does society place too much importance on sports?   
24          28             What is best way to make money online?   
25          29             How should I prepare for CA final law?   
26          30      What's one thing you would like to do better?   
27          31  What are some special cares for someone with a...   
28          32  What Game of Thrones villain would be the most...   
29          33  Does the United States government still blackl...   
...        ...                                                ...   
323134  404253             How do I make website like fmovies.to?   
323135  404255                 Does IBM Watson use ElasticSearch?   
323136  404256  What are some of the most common questions ask...   
323137  404257             What is Bitcoin? Is it legal in India?   
323138  404258  What is the difference between a psychologist ...   
323139  404259  What do you think is wrong with Indian schools...   
323140  404260                   Which phone is best under 12000?   
323141  404261  Who is the overall most popular Game of Throne...   
323142  404262          How do you troubleshoot a Toshiba laptop?   
323143  404266  What is the green dot next to the phone icon o...   
323144  404267  What are the causes of the fall of the Roman E...   
323145  404268  Why don't we still do great music like in the ...   
323146  404271  Does Stalin have any grandchildren that are st...   
323147  404272  What are the best new car products or inventio...   
323148  404273    What happens if you put milk in a coffee maker?   
323149  404274  Will the next generation of parenting change o...   
323150  404275  In accounting, why do we debit expenses and cr...   
323151  404276                         What is copilotsearch.com?   
323152  404277                            What does analytics do?   
323153  404279  What is the minimum time required to build a f...   
323154  404280  What are some outfit ideas to wear to a frat p...   
323155  404281  Why is Manaphy childish in Pokémon Ranger and ...   
323156  404282        How does a long distance relationship work?   
323157  404283  What do you think of the removal of the MagSaf...   
323158  404284         What does Jainism say about homosexuality?   
323159  404285  How many keywords are there in the Racket prog...   
323160  40

In [304]:
#train_set.to_csv('Data/fuzz.csv')

In [278]:
#train_set = pd.read_csv("Data/fuzz.csv")

In [305]:
# remove nans
train_set = train_set[train_set['fuzzTokenSet'].isnull() == False]
train_set = train_set[train_set['fuzzRatio'].isnull() == False]
train_set = train_set[train_set['fuzzPartial'].isnull() == False]
train_set = train_set[train_set['fuzzTokenSort'].isnull() == False]
train_set

id                                          question1  \
0            0  What is the step by step guide to invest in sh...   
1            1  What is the story of Kohinoor (Koh-i-Noor) Dia...   
2            2  How can I increase the speed of my internet co...   
3            3  Why am I mentally very lonely? How can I solve...   
4            4  Which one dissolve in water quikly sugar, salt...   
5            5  Astrology: I am a Capricorn Sun Cap moon and c...   
6            6                                Should I buy tiago?   
7            7                     How can I be a good geologist?   
8            8                    When do you use シ instead of し?   
9            9  Motorola (company): Can I hack my Charter Moto...   
10          10  Method to find separation of slits using fresn...   
11          11        How do I read and find my YouTube comments?   
12          12               What can make Physics easy to learn?   
13          13        What was your first sexual experience like?   
14          14  What are the laws to change your status from a...   
15          16                       What does manipulation mean?   
16          17  Why do girls want to be friends with the guy t...   
17          18  Why are so many Quora users posting questions ...   
18          19  Which is the best digital marketing institutio...   
19          22    What are the questions should not ask on Quora?   
20          24  What does it mean that every time I look at th...   
21          25  What are some tips on making it through the jo...   
22          26                           What is web application?   
23          27  Does society place too much importance on sports?   
24          28             What is best way to make money online?   
25          29             How should I prepare for CA final law?   
26          30      What's one thing you would like to do better?   
27          31  What are some special cares for someone with a...   
28          32  What Game of Thrones villain would be the most...   
29          33  Does the United States government still blackl...   
...        ...                                                ...   
323134  404253             How do I make website like fmovies.to?   
323135  404255                 Does IBM Watson use ElasticSearch?   
323136  404256  What are some of the most common questions ask...   
323137  404257             What is Bitcoin? Is it legal in India?   
323138  404258  What is the difference between a psychologist ...   
323139  404259  What do you think is wrong with Indian schools...   
323140  404260                   Which phone is best under 12000?   
323141  404261  Who is the overall most popular Game of Throne...   
323142  404262          How do you troubleshoot a Toshiba laptop?   
323143  404266  What is the green dot next to the phone icon o...   
323144  404267  What are the causes of the fall of the Roman E...   
323145  404268  Why don't we still do great music like in the ...   
323146  404271  Does Stalin have any grandchildren that are st...   
323147  404272  What are the best new car products or inventio...   
323148  404273    What happens if you put milk in a coffee maker?   
323149  404274  Will the next generation of parenting change o...   
323150  404275  In accounting, why do we debit expenses and cr...   
323151  404276                         What is copilotsearch.com?   
323152  404277                            What does analytics do?   
323153  404279  What is the minimum time required to build a f...   
323154  404280  What are some outfit ideas to wear to a frat p...   
323155  404281  Why is Manaphy childish in Pokémon Ranger and ...   
323156  404282        How does a long distance relationship work?   
323157  404283  What do you think of the removal of the MagSaf...   
323158  404284         What does Jainism say about homosexuality?   
323159  404285  How many keywords are there in the Racket prog...   
323160  40

# Random Forest Classifier

In [334]:
train, test = train_test_split(train_set, test_size=0.2)

In [335]:
print('N training data:', len(train))
print('N test data:',len(test))

N training data: 258531
N test data: 64633


In [336]:
clf = RandomForestClassifier(n_jobs=1, random_state=0)

In [337]:
#simArray = np.array(train['similarity']).reshape((-1, 1))
#simArray = [[(np.float32(x[0]))] for x in simArray]
#simArray

In [338]:
#len(simArray), len(train['is_duplicate_y'])

In [339]:
features = train.columns[-4:]
features

Index(['fuzzRatio', 'fuzzPartial', 'fuzzTokenSort', 'fuzzTokenSet'], dtype='object')

In [340]:
clf.fit(train[features], train['is_duplicate_y'])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [341]:
#simY = np.array(train['similarity']).reshape((-1, 1))
#simY = [[(np.float32(x[0]))] for x in simY]
#simY

In [342]:
prediction = clf.predict(train[features])
prediction

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [343]:
clf.predict_proba(train[features])

array([[0.9, 0.1],
       [1. , 0. ],
       [1. , 0. ],
       ...,
       [1. , 0. ],
       [1. , 0. ],
       [1. , 0. ]])

In [344]:
np.array(test['is_duplicate_y'])

array([0, 0, 1, ..., 1, 0, 0], dtype=int64)

In [345]:
acc = sklearn.metrics.accuracy_score(prediction, np.array(np.array(train['is_duplicate_y'])))

print (acc)

0.9179827564199264


In [346]:
prediction = clf.predict(test[features])
prediction

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [347]:
acc = sklearn.metrics.accuracy_score(prediction, np.array(np.array(test['is_duplicate_y'])))

print (acc)

0.6718239908405923
